@extends('layouts.app')
@section('title','Overview')
@section('content')
<div class="page-heading"><div><span class="eyebrow">{{ now(config('clinobserve.timezone'))->format('l, d F Y') }}</span><h1>Your learning workspace</h1><p class="text-muted">A clear view of {{ auth()->user()->isHod()?'your department’s clinical learning activity.':'your observations, reflections and progress.' }}</p></div><a class="btn btn-primary" href="{{ route(auth()->user()->isHod()?'hod.students.create':'patients.create') }}">+ {{ auth()->user()->isHod()?'Add student':'Add patient case' }}</a></div>
<div class="hero-strip"><div><span class="badge bg-white text-primary mb-3">LEARNING THROUGH OBSERVATION</span><h2>{{ auth()->user()->isHod()?'Help every student move forward.':'Small observations. Meaningful progress.' }}</h2><p>{{ auth()->user()->isHod()?'Review observations, share perspective and guide the next generation.':'Record what you notice. Ask better questions. Reflect with your faculty.' }}</p><a href="{{ route('encounters.index') }}" class="btn btn-light">Explore observations →</a></div><div class="hero-art" aria-hidden="true"><div class="orbit"></div><span>+</span><div class="pulse-line"></div></div></div>
<div class="stats-grid">@foreach($stats as $label=>$value)<div class="stat-card"><span>{{ $label }}</span><strong>{{ $value }}</strong><small>Academic activity</small></div>@endforeach</div>
<div class="content-card"><div class="section-heading"><div><h2>Recent observations</h2><p class="text-muted mb-0">Clinical learning, one encounter at a time.</p></div><a href="{{ route('encounters.index') }}">View all →</a></div><x-encounter-table :encounters="$recent"/></div>
<div class="row g-4 mt-0"><div class="col-lg-6"><div class="content-card h-100"><h2>Faculty feedback</h2>@forelse($feedback as $review)<a class="activity-item" href="{{ route('hod-reviews.show',$review) }}"><span class="avatar">F</span><div><strong>{{ $review->encounter->patient->display_name }}</strong><p>{{ str($review->comment)->limit(110) }}</p><small>{{ $review->hod->name }} · {{ $review->created_at->diffForHumans() }}</small></div></a>@empty<div class="empty-state">Faculty feedback will appear here after an observation is reviewed.</div>@endforelse</div></div>
<div class="col-lg-6"><div class="content-card h-100"><h2>AI educational reviews</h2>@forelse($aiReviews as $review)<a class="activity-item" href="{{ route('ai-reviews.show',$review) }}"><span class="avatar lavender">✧</span><div><strong>{{ $review->encounter->patient->display_name }}</strong><p>{{ ucfirst($review->status) }}</p><small>{{ $review->created_at->diffForHumans() }}</small></div></a>@empty<div class="empty-state">Optional educational suggestions appear here when you request an AI review.</div>@endforelse</div></div></div>
@can('hod')<div class="content-card mt-4"><div class="section-heading"><h2>Department pulse</h2><span class="badge text-bg-warning">{{ $pending }} awaiting faculty feedback</span></div><p class="text-muted">Students with encounters in the last 30 days</p><div class="d-flex gap-3 flex-wrap">@forelse($activeStudents as $student)<a class="student-chip" href="{{ route('hod.students.show',$student) }}">{{ $student->name }} <span class="badge text-bg-light">{{ $student->encounters_count }}</span></a>@empty<p>No recent activity.</p>@endforelse</div></div>@endcan
@endsection


