@extends('layouts.app')
@section('title','Observation')
@section('content')
<div class="page-heading"><div><span class="eyebrow">ENCOUNTER #{{ $encounter->id }}</span><h1>{{ $encounter->patient->display_name }}</h1><p class="text-muted">{{ $encounter->student->name }} · {{ $encounter->attended_at->timezone(config('clinobserve.timezone'))->format('d M Y, h:i A') }}</p></div><div>@can('update',$encounter)<a class="btn btn-light" href="{{ route('encounters.edit',$encounter) }}">Edit observation</a>@endcan @can('requestAi',$encounter)<a class="btn btn-primary" href="{{ route('ai-reviews.preview',$encounter) }}">✧ AI review</a>@endcan</div></div>
@if($encounter->locked_at)<div class="alert alert-light border">This observation is locked because faculty feedback or an AI request has been recorded. Add a new encounter for subsequent observations.</div>@endif
<div class="content-card">@foreach(\App\Models\PatientEncounter::FIELDS as $field)@if($encounter->$field)<h3>{{ str($field)->replace('_',' ')->title() }}</h3><p class="preserve mb-4">{{ $encounter->$field }}</p>@endif
@endforeach<a href="{{ route('patients.show',$encounter->patient) }}">← Complete case timeline</a></div>
<div class="content-card mt-4"><h2>Encounter images</h2><div class="image-grid">@forelse($encounter->images as $image)<div><a href="{{ route('encounter-images.show',$image) }}"><img src="{{ route('encounter-images.show',$image) }}" alt="De-identified observation image"></a>@can('delete',$image)<form method="post" action="{{ route('encounter-images.destroy',$image) }}" data-confirm="Remove this image?">@csrf @method('DELETE')<button class="btn btn-sm btn-outline-danger mt-2">Remove</button></form>@endcan</div>@empty<p class="text-muted">No images attached.</p>@endforelse</div>
@can('update',$encounter)<form class="mt-4" method="post" enctype="multipart/form-data" action="{{ route('encounter-images.store',$encounter) }}">@csrf<label class="form-label" for="images">Add images (five total; 5 MiB each)</label><input class="form-control mb-3" id="images" type="file" name="images[]" accept="image/png,image/jpeg,image/webp" multiple required><button class="btn btn-outline-primary">Upload images</button></form>@endcan</div>
@if($private)<div class="row g-4 mt-0"><div class="col-lg-7"><div class="content-card"><h2>Private faculty feedback</h2><p class="small text-muted">Visible to the student, their assigned professor and HOD users.</p>@forelse($encounter->hodReviews as $review)<article class="feedback-card"><p class="preserve">{{ $review->comment }}</p><small>{{ $review->hod->name }} · {{ $review->created_at->format('d M Y') }}</small><a class="d-block mt-2" href="{{ route('hod-reviews.show',$review) }}">Open feedback →</a></article>@empty<p class="text-muted">Awaiting faculty review.</p>@endforelse
@can('review', $encounter)<form class="mt-4" method="post" action="{{ route(auth()->user()->isHod()?'hod.reviews.store':'professor.reviews.store',$encounter) }}">@csrf<x-field name="comment" label="Your feedback" type="textarea" required maxlength="5000"/><button class="btn btn-primary">Add faculty feedback</button></form>@endcan</div></div>
<div class="col-lg-5"><div class="content-card"><h2>AI review history</h2>@forelse($encounter->aiReviews as $review)<a class="activity-item" href="{{ route('ai-reviews.show',$review) }}"><div><strong>Review #{{ $review->id }}</strong><p>{{ ucfirst($review->status) }} · {{ $review->created_at->format('d M Y, H:i') }}</p></div></a>@empty<p class="text-muted">No AI reviews requested.</p>@endforelse</div></div></div>@endif
@endsection


