@extends('layouts.app')
@section('title','Patient cases')
@section('content')
<div class="page-heading"><div><span class="eyebrow">SHARED CLINICAL LEARNING</span><h1>Patient cases</h1><p class="text-muted">Explore de-identified cases and build on previous observations.</p></div><a class="btn btn-primary" href="{{ route('patients.create') }}">+ Add case</a></div>
<div class="content-card"><form class="row g-3 align-items-end mb-4" method="get"><div class="col-md-5"><x-field name="q" label="Search cases" :value="request('q')" placeholder="Case number or display name"/></div><div class="col-md-3"><x-field name="condition" :value="request('condition')" placeholder="Condition or learning topic"/></div><div class="col-md-2"><x-select name="gender" label="Gender" :value="request('gender')" :options="['female'=>'Female','male'=>'Male','other'=>'Other','unknown'=>'Unknown','undisclosed'=>'Undisclosed']"/></div><div class="col-md-2 mb-3"><button class="btn btn-outline-primary w-100">Search</button></div></form>
<div class="table-responsive"><table class="table align-middle"><thead><tr><th>Case</th><th>Age / gender</th><th>Admission</th><th>Encounters</th><th>Last observed</th><th></th></tr></thead><tbody>@forelse($patients as $patient)<tr><td><a class="fw-semibold" href="{{ route('patients.show',$patient) }}">{{ $patient->display_name }}</a><small class="d-block text-muted">{{ $patient->case_number }}</small></td><td>{{ $patient->age_years }} years · {{ ucfirst($patient->gender) }}</td><td>{{ $patient->admission_date->format('d M Y') }}</td><td><span class="badge rounded-pill text-bg-light">{{ $patient->encounters_count }}</span></td><td>{{ $patient->encounters_max_attended_at ? \Carbon\Carbon::parse($patient->encounters_max_attended_at)->timezone(config('clinobserve.timezone'))->format('d M Y') : 'Not yet observed' }}</td><td><a href="{{ route('patients.show',$patient) }}">Open →</a></td></tr>@empty<tr><td colspan="6" class="empty-state">No cases found. Add a synthetic case to start learning.</td></tr>@endforelse</tbody></table></div>{{ $patients->links() }}</div>
@endsection


