@extends('layouts.app')
@section('title',$student->name)
@section('content')
<div class="page-heading"><div><span class="eyebrow">STUDENT PROFILE</span><h1>{{ $student->name }}</h1><p class="text-muted">{{ $student->email }} · {{ $student->studentProfile?->roll_number }}</p></div>@can('update', $student)<a class="btn btn-primary" href="{{ route('hod.students.edit',$student) }}">Edit academic details</a>@endcan</div>
<div class="row g-4"><div class="col-lg-8"><div class="content-card"><h2>Biodata</h2><p class="text-muted">Assigned professor: {{ $student->professor?->name ?? 'Unassigned' }}</p>@if($student->studentProfile?->avatar_path)<img class="profile-photo mb-3" src="{{ route('students.avatar',$student) }}" alt="Student profile image">@endif<div class="row">@foreach(['roll_number','registration_number','batch','academic_year','college','course','department','joining_year','phone','gender','address','bio'] as $field)<div class="col-md-6 mb-3"><h3>{{ str($field)->replace('_',' ')->title() }}</h3><p class="preserve mb-0">{{ $student->studentProfile?->$field??'Not provided' }}</p></div>@endforeach<div class="col-md-6"><h3>Date of birth</h3><p>{{ $student->studentProfile?->date_of_birth?->format('d M Y')??'Not provided' }}</p></div></div><a class="btn btn-light" href="{{ route(auth()->user()->isHod()?'hod.calendar.index':'calendar.index',['student_id'=>$student->id]) }}">View learning calendar →</a></div></div>
@can('update', $student)<div class="col-lg-4"><div class="content-card"><h2>Account access</h2><p><span class="badge {{ $student->is_active?'text-bg-success':'text-bg-secondary' }}">{{ $student->is_active?'Active':'Inactive' }}</span></p><form method="post" action="{{ route('hod.students.status.update',$student) }}" data-confirm="Change this student's access? Existing sessions will end.">@csrf @method('PATCH')<input type="hidden" name="is_active" value="{{ $student->is_active?0:1 }}"><button class="btn btn-outline-secondary">{{ $student->is_active?'Deactivate':'Activate' }} account</button></form><hr><h3>Reset credentials</h3><form method="post" action="{{ route('hod.students.credentials.update',$student) }}" data-confirm="Reset the password and revoke existing sessions?">@csrf @method('PUT')<x-field name="password" label="Temporary password" type="password" required minlength="12"/><x-field name="password_confirmation" label="Confirm password" type="password" required/><button class="btn btn-outline-primary">Reset password</button></form></div></div>@endcan</div>
<div class="content-card mt-4"><h2>Student encounters</h2><x-encounter-table :encounters="$encounters"/>{{ $encounters->links() }}</div>
@endsection


